### ISSUE TITLE
phone died, [no access to group chat ]

### ISSUE THREAD

**Issue by ghost** [DaveLominski/RealWorldProject#3]
yeah, phone died, and its in for repairs. I have no idea how long it will take. Replacement is a "dumb" phone so no whats app access.

If there's anything I can do or suggestions please message me in this issue form...

*** PS - DONT CLOSE IT, ILL DO THAT WHEN MY PHONE IS BACK ***

**Comment by DaveLominski** [comment]
Just because your phone is in repair doesn't mean you can't attend monday sessions ...

**Comment by ghost** [comment]
That was not Mondays reason, my uncial is disabled and need to go to the hospital. my granddad was not well with is breathing so I when with him.

Today: was my own fault, so I'm 100% responsible.

Ill come to Wednesday afternoon or when ever.

**Comment by ghost** [comment]
Is there anything i can do in the meantime ?

**Comment by ghost** [comment]
also what was spoken about on Mondays session...

**Comment by ghost** [comment]
Oh yeah i meant my granddad was no in good health so I had to take my uncial to the hospital.

**Comment by DaveLominski** [comment]
Josh you have to come in on Monday and Wednesday. We will be discussing things for the video on Monday, and on Wednesday we will be recording bits and bobs for the video. Already got a room booked in the library for 3:30.

**Comment by ghost** [comment]
OK, 3:30 is for Wednesday ?
